package command

/*命令分2种， 100开始 100以下为系统
1,无ON开始的为发送
2,回答的为ON开始
*/

const COMMAND_BEGIN_INT = 100

//cmds
const (
	_ int = 300 + iota
	CLIENT_LOGON
	CLIENT_LOGOUT
	SERVER_LOGON_RESULT
	SERVER_KICK_PLAYER
)

//world
const (
	_ int = 400 + iota
	SERVER_WORLD_REMOVE_PLAYER
	SERVER_WORLD_ADD_PLAYER
	SERVER_WORLD_NOTICE_PLAYERS
	//暗渡陈仓
	SERVER_WORLD_KICK_PLAYER
	SERVER_WORLD_GET_ONLINE_NUM
	SERVER_WORLD_NOTICE_TEST
)

//chat
const (
	_ int = 500 + iota
	CLIENT_JOIN_CHANNEL
	CLIENT_QUIT_CHANNEL
	CLIENT_NOTICE_CHANNEL
	//服务器和客户端都能使用
	SERVER_BUILD_CHANNEL
	SERVER_REMOVE_CHANNEL
)

//hall
const (
	_ int = 600 + iota
	CLIENT_CHANGE_NAME
	CLIENT_CHANGE_INFO
)

//game
const (
	_ int = 1000 + iota
	CLIENT_GAME_ENTER
	CLIENT_GAME_RECONNENT
	CLIENT_GAME_LEAVE
	CLIENT_GAME_DROPS
	CLIENT_GAME_MESSAGE //照样广播
	CLIENT_GAME_SIT
	CLIENT_GAME_STAND
	CLIENT_GAME_TABLE_INFO
	//广播
	SERVER_BROADCAST_GAME_ENTER
	SERVER_BROADCAST_GAME_LEAVE
	SERVER_BROADCAST_GAME_SIT
	SERVER_BROADCAST_GAME_STAND
	//服务器调度
	SERVER_OPEN_TABLE
	SERVER_STOP_TABLE
	//
	SERVER_ADD_PLAYER
	SERVER_DEL_PLAYER
)

//game texas
const (
	_ int = 1100 + iota
	//具体texas
	CLIENT_TEXAS_USER_BET
	CLIENT_TEXAS_MESSAGE
	SERVER_TEXAS_START      //游戏开始
	SERVER_TEXAS_BET_START  //通知开始下注
	SERVER_TEXAS_BET_RESULT //通知下注结果
	SERVER_TEXAS_TURN       //回合结束
	SERVER_TEXAS_OVER       //游戏结束
	SERVER_TEXAS_RESULT     //奖励
)

//game niuniu
const (
	_ int = 1200 + iota
	//具体texas
	CLIENT_NIUNIU_MESSAGE
	CLIENT_NIUNIU_BANKER       //抢庄
	CLIENT_NIUNIU_BET          //下注
	CLIENT_NIUNIU_COMMIT       //提交
	SERVER_NIUNIU_START        //游戏开始(开始抢庄)
	SERVER_NIUNIU_USER_CARDS   //自己的牌
	SERVER_NIUNIU_BET_START    //通知下注开始(确定庄)
	SERVER_NIUNIU_COMMIT_START //通知提交开始
	SERVER_NIUNIU_OVER         //游戏结束(提交结束)
	SERVER_NIUNIU_RESULT       //奖励分配
)

//RPG
const (
	_ int = 100100 + iota
	CLIENT_MOVE
	CLIENT_ACTION
	CLIENT_RESULT
)
